### PR TITLE
Recursively check unique pkg names against existing imports

### LINKED ISSUE #184: Moq creates non-unique import aliases
In one of our projects I have an, admittedly quite exotic, edge-case where we're mocking an interface from another package and the transient imports all have the same package name at the end of the path. The conflict resolve mechanism for aliases doesn't work in this case, as it only looks at 2 conflicting packages at a time.

To reproduce it requires at least 4 imports and you need to be mocking an interface from another package, so not setting unique aliases yourself.

**Mocked Interface**
```
package transientimport

import (
	"github.com/matryer/moq/pkg/moq/testpackages/transientimport/base"
)

type Transient = base.Transient
```

**Original Interface**
```
package base

import (
	four "github.com/matryer/moq/pkg/moq/testpackages/transientimport/four/app/v1"
	one "github.com/matryer/moq/pkg/moq/testpackages/transientimport/one/v1"
	three "github.com/matryer/moq/pkg/moq/testpackages/transientimport/three/v1"
	two "github.com/matryer/moq/pkg/moq/testpackages/transientimport/two/app/v1"
)

type Transient interface {
	DoSomething(one.One, two.Two, three.Three, four.Four)
}
```

The origin is that we're using an interface from the `k8s.io/client-go/kubernetes` package and want to use mocks of that interface in our tests.

I put together a test case and possible solution here:
https://github.com/cldmstr/moq/tree/unique-import-aliases

### PR DESCRIPTION
**Pull request by sudo-suhas**
When we generate a unique name for pkg a on conflict with pkg b, the new name could already be in use for pkg c. So recursively check each unique name against existing imports before setting it.

Closes #184 

/cc @cldmstr

### CODE REVIEW

**Comment by sudo-suhas** [comment]
@matryer @breml will wait for your review until this weekend to merge this change. Will tag and release `v0.3.0` post that.

File: internal/registry/registry.go [hunk 1]
```diff
@@ -126,6 +126,30 @@ func (r Registry) searchImport(name string) (*Package, bool) {
 	return nil, false
 }
 
+// resolveImportConflict generates and assigns a unique alias for
+// packages with conflicting qualifiers.
+func (r Registry) resolveImportConflict(a, b *Package, lvl int) {
```
Comment (breml) [inline internal/registry/registry.go:131]: While reviewing this code I wondered, if there are simpler ways to get a unique import alias. Two ideas I would like to share:

1. Instead of adding more levels of the import path to the alias only when needed, always add all the levels, because as mentioned in the comment of `uniqueName`, the full path is guaranteed to be unique.
1. Generate a hash from the full import path and appending some characters (similar to the shortened git hashes) from the hash to the original package name resulting in something like `pkg_a3b295`.

I think, with both approaches, the process for generating the aliases is straight forward without the need for any recursion and comparing.

In the end the code that is generated by `moq` is not intended to be as readable as possible by humans, where this code is written by humans and for humans.

**Review by breml — APPROVED** [review]
LGTM, but I think the algorithm for selecting an alias could be simplified. Because we are talking about generated code, I would argue, that this might be worth the price for the reduced readability of the generated code (see my inline comment for details).

File: internal/registry/registry.go (hunk 1 above)
Comment (sudo-suhas) [reply internal/registry/registry.go:131]: The current way of identifying an appropriate alias has had bugs and needed multiple patches. This clearly indicates that the problem is a bit difficult to fully understand and apply to all the different scenarios in practice. So there would definitely be justification for generating aliases that are guaranteed to not conflict.

However, I think one of the strengths of `moq` is that it generates code that looks hand-written with the benefit of readable and meaningful names with helpful comments. To that effect, I think there is value in bearing the cost of maintenance to a reasonable degree. This change is close to that limit though. So if more issues arise, would strongly consider moving in the direction suggested by you.

Hope that made sense.

**Comment by sudo-suhas** [comment]
Released in [v0.3.0](https://github.com/matryer/moq/releases/tag/v0.3.0) 🎉
